### ISSUE TITLE
Sequence error

### ISSUE THREAD

**Issue by tortho** [eibakke/hass_scripts#1]
Unable to get this to work, only changed the nordpool sensor in cheapest_hours_energy.py to reflect my sensor in the following
(and created the local calendar entity calendar.electricity)

nordpool_sensor_id = data.get("nordpool_sensor_id", "sensor.nordpool")

Error log
2023-06-28 16:55:02.085 ERROR (SyncWorker_3) [homeassistant.components.python_script.cheapest_hours_energy.py] Error executing script: sequence item 0: expected str instance, NoneType found
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 224, in execute
exec(compiled.code, restricted_globals)
File "cheapest_hours_energy.py", line 128, in <module>
File "cheapest_hours_energy.py", line 126, in setCheapestHours
File "cheapest_hours_energy.py", line 89, in createEventsForSequences
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by eibakke** [comment]
The `TypeError: sequence item 0: expected str instance, NoneType found` error comes from the join function call in the createEventsForSequences function. The relevant line:

`desc = ":".join([service_to_call, start_method, end_method, automate_entity_id])`

This line is creating the calendar event description, which contains the automation that should happen with the calendar event starting and ending. Check out the `calendar_automations.py` script for how the string is interpreted. The error is saying that the first index in the list passed to the join function call is None, but it should be a string. Populating the `service_to_call`, `start_method`, `end_method`, and `automate_entity_id` flags in your service call will fix your issue.

Of course, not populating these flags should not lead to an error, I'll get to that at some point.

**Comment by eibakke** [comment]
Added flag validation with more meaningful error messages.
